[project]
name = "py-initseq"
version = "0.1.0"
description = "Initial sequence method for autocorrelation estimation."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pyqt6>=6.11.0",
    "scipy>=1.18.1",
]

[build-system]
requires = ["uv_build>=0.12.19,<0.13"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["ALL"]

